bash test2.sh warpx nocomp
bash test2.sh warpx zlib
#bash test2.sh warpx cbb
bash test2.sh ferrox nocomp
bash test2.sh ferrox zlib
#bash test2.sh ferrox cbb
bash test2.sh nyx nocomp
bash test2.sh nyx zlib
#bash test2.sh nyx cbb
bash test2.sh maestroex nocomp
bash test2.sh maestroex zlib
#bash test2.sh maestroex cbb